name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - master
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESSTOKEN }}
          secrets: |
            5ee4be7a-2646-49de-a60c-b20200a788c9 > DOCKER_USERNAME
            bad03c0d-c8d0-49de-815f-b202008519ad > DOCKER_PASSWORD
    
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hackwknd-api:${{ github.sha }} -f ./Dockerfile .

      # Tag the Docker image (optional)
      - name: Tag Docker image with latest
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/hackwknd-api:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/hackwknd-api:latest

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hackwknd-api:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/hackwknd-api:latest
